# Generated by Django 5.1.2 on 2024-11-19 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 11, 19, 10, 8, 24, 985452, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 11, 19, 10, 8, 24, 986243, tzinfo=datetime.timezone.utc)),
        ),
    ]
